In [3]:
import pandas as pd
df = pd.read_csv("winequality-white.csv",sep=';')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [4]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [5]:
import pandas as pd
import numpy as np

rs = np.random.RandomState(0)
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [ ]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))

In [20]:
X, y = df.iloc[:,:-1], df.iloc[:,-1]
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
4893     11.2  
4894      9.6  
4895      9.4  
4896     12.8  
4897     11.8  

[4898 rows x 11 columns]

In [21]:
y

0       6
1       6
2       6
3       6
4       6
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 4898, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [43]:
scaler = StandardScaler()
x = scaler.fit_transform(X_train)


array([[-1.49330341,  0.00887785,  0.5494557 , ...,  0.13483547,
        -0.52368369,  1.28829071],
       [ 1.69849482,  1.29249418,  1.46103085, ..., -1.12839094,
         0.53324035,  0.71998866],
       [-1.84794766,  0.305097  ,  0.38371477, ...,  0.99914828,
        -0.25945268,  0.96354668],
       ...,
       [ 0.87099157, -0.08986187,  1.54390132, ..., -1.12839094,
         0.35708635,  0.71998866],
       [-0.66580017, -0.38608103, -0.36211944, ..., -0.13110693,
        -0.96406871,  0.0705006 ],
       [ 1.46206532, -0.08986187,  0.13510336, ...,  0.20132107,
         1.23785638, -0.09187142]])

In [44]:
import joblib
joblib.dump(scaler, 'scaler.joblib')  

['scaler.joblib']

In [46]:
model = joblib.load('scaler.joblib')
x = model.fit_transform(X_train)

In [47]:
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np
regr = SVR(C=1.0, epsilon=0.2)
regr.fit(x, y_train)

SVR(epsilon=0.2)

In [53]:
x_t = scaler.transform(X_test)
x_t

array([[-0.99823869,  0.13536497,  0.61475668, ..., -0.62665859,
         0.86198465,  0.36658813],
       [-1.71322978,  2.54124714, -1.43976868, ...,  0.0965216 ,
         0.34147833,  2.18531827],
       [ 0.3125783 , -0.26561539,  0.45039465, ...,  0.62247083,
        -0.52603221,  1.37096149],
       ...,
       [ 0.07424794, -0.96733102,  0.36821364, ..., -0.56091493,
        -0.61278326, -0.01344503],
       [ 0.90840421,  0.33585515, -0.78232057, ..., -0.8896332 ,
        -0.43928116,  1.04521878],
       [-0.2832476 , -0.06512521, -0.37141549, ...,  0.8197018 ,
         2.59700573, -0.58349477]])

In [52]:
x_t = scaler.transform(X_test)
regr.predict(x_t)

array([6.10501176, 6.76105124, 6.65479769, ..., 5.98937476, 6.0776082 ,
       5.70923975])

In [49]:
import joblib
joblib.dump(regr, 'model.joblib')  

['model.joblib']

In [51]:
model = joblib.load('model.joblib')
model.predict(x_t)

array([6.10501176, 6.76105124, 6.65479769, ..., 5.98937476, 6.0776082 ,
       5.70923975])

In [35]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
mean_squared_error(regr.predict(X_test), y_test)

0.4759392979539604

In [36]:
mean_absolute_error(regr.predict(X_test), y_test)

0.5269547955743501

In [29]:
import pickle 
  
# Save the trained model as a pickle string. 
saved_model = pickle.dumps(regr) 

In [30]:
import joblib 
  
# Save the model as a pickle in a file 
joblib.dump(saved_model, 'svmdj.pkl') 
  
# Load the model from the file 
load_model = joblib.load('svmdj.pkl')

In [31]:
load_model.predict(X_test)

AttributeError: 'bytes' object has no attribute 'predict'

In [32]:
filename = 'finalized_model.sav'
pickle.dump(regr, open(filename, 'wb'))
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.predict(X_test)

array([6.0814287 , 6.75030891, 6.63253626, ..., 5.98610082, 6.06914551,
       5.71022104])

In [33]:
loaded_model

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(epsilon=0.2))])

In [37]:
X.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [39]:
import joblib
joblib.dump(regr, 'final_model.joblib')  

['final_model.joblib']

In [42]:
model = joblib.load('final_model.joblib')
model.predict(X_test[:1])

array([6.0814287])

In [55]:
import sklearn
sklearn.__version__

'0.23.0'

In [57]:
joblib.__version__w

'0.14.1'